[build-system]
requires = [
    "robotpy-build<2025.0.0,~=2024.0.0b2",
    "robotpy-wpiutil<2025.0.0,>=2024.0.0b3.post1",
    "robotpy-wpimath<2025.0.0,>=2024.0.0b3.post1",
    "wpilib<2025.0.0,>=2024.0.0b3.post1",
]

[tool.robotpy-build.metadata]
name = "robotpy-photonvision"
description = "RobotPy wrappers for photonvision"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-photonvision"
license = "MIT"
install_requires = [
    "robotpy-wpiutil<2025.0.0,>=2024.0.0b3.post1",
    "robotpy-wpimath<2025.0.0,>=2024.0.0b3.post1",
    "wpilib<2025.0.0,>=2024.0.0b3.post1",
]

[tool.robotpy-build]
base_package = "photonvision"

[tool.robotpy-build.static_libs."photonvision-opencv".maven_lib_download]
artifact_id = "opencv-cpp"
group_id = "edu.wpi.first.thirdparty.frc2024.opencv"
repo_url = "https://frcmaven.wpi.edu/artifactory/release"
version = "4.8.0-2"

libs = ["opencv480"]

[tool.robotpy-build.wrappers."photonvision".maven_lib_download]
artifact_id = "PhotonLib-cpp"
group_id = "org.photonvision"
repo_url = "https://maven.photonvision.org/repository/internal"
version = "v2024.1.1-beta-3.2"

use_sources = true
sources = [
    "photonlib/PhotonCamera.cpp",
    "photonlib/PhotonPipelineResult.cpp",
    "photonlib/PhotonPoseEstimator.cpp",
    "photonlib/PhotonTrackedTarget.cpp",
    "photonlib/MultiTargetPNPResult.cpp",
]


[tool.robotpy-build.wrappers."photonvision"]
name = "photonvision"

depends = [
    "wpilibc",
    "wpilib_core",
    "wpimath_cpp",
    "wpiHal",
    "wpiutil",
    "wpimath_geometry",
]

sources = [
    "photonvision/src/module.cpp",
]

generation_data = "gen"

[tool.robotpy-build.wrappers."photonvision".autogen_headers]
# photonlib
Packet = "photonlib/Packet.h"
PhotonCamera = "photonlib/PhotonCamera.h"
PhotonPipelineResult = "photonlib/PhotonPipelineResult.h"
PhotonPoseEstimator = "photonlib/PhotonPoseEstimator.h"
PhotonTargetSortMode = "photonlib/PhotonTargetSortMode.h"
PhotonTrackedTarget = "photonlib/PhotonTrackedTarget.h"
PhotonUtils = "photonlib/PhotonUtils.h"
SimPhotonCamera = "photonlib/SimPhotonCamera.h"
SimVisionSystem = "photonlib/SimVisionSystem.h"
SimVisionTarget = "photonlib/SimVisionTarget.h"
MultiTargetPNPResult = "photonlib/MultiTargetPNPResult.h"
