[tool.robotpy-build.metadata]
name = "robotpy-photonvision"
description = "RobotPy wrappers for PhotonVision"
author = "RobotPy Development Team"
author_email = "robotpy@googlegroups.com"
url = "https://github.com/robotpy/robotpy-photonvision"
license = "MIT"

install_requires = [
    "wpilib~=2025.0.0b1",
    "robotpy-wpinet~=2025.0.0b1",
    "robotpy-apriltag~=2025.0.0b1",
]


[build-system]
requires = [
    "robotpy-build<2025.0.0b1,~=2025.0.0a1",
    "robotpy-wpinet~=2025.0.0b1",
    "wpilib~=2025.0.0b1",
    "robotpy-apriltag~=2025.0.0b1",
]


[tool.robotpy-build]
base_package = "photontargeting"


[tool.robotpy-build.wrappers."photonvision.targeting"]
name = "photonvision_targeting"

depends = [
    "wpinet",
    "wpiutil",
    "wpimath_cpp",
    "wpilib_core"
]

generation_data = "gen/photontargeting"


[tool.robotpy-build.wrappers."photonvision.targeting".maven_lib_download]
artifact_id = "photontargeting-cpp"
group_id = "org.photonvision"
repo_url = "https://maven.photonvision.org/snapshots"
version = "dev-v2025.0.0-beta-2-6-g5f3dc152"
libs = ["photontargeting"]


[tool.robotpy-build.wrappers."photonvision.targeting".autogen_headers]
TimeSyncClient = "net/TimeSyncClient.h"
